name: Main-Lint-Test-Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    MainLintTestBuild:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: node_modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Package
              run: npm ci

            - name: Start Lint
              run: npm run all

            - name: Start Test
              run: npm run test

            - name: Start Build
              run: npm run build
